language: node_js
node_js:
  - "8.11.3"
cache:
  - directories:
    - node_modules

jobs:
  include:
    - stage: "Tests"
      name: "Web Production Build Test"
      script:
        - npm install
        - npm run build