name: Build Windows Client

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Clone source code
        uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install dependencies and build
        run: |
          npm install
          npm run build --if-present
          npm run build-desktop-win